### ISSUE TITLE
install_enabled var is ignored / treated as always true

### ISSUE THREAD

**Issue by vasekhodina** [markt-de/puppet-nextcloud#11]
Hello,
it looks like nextcloud::install_enabled is ignored.
I have the following setup in hiera:
```
---
profile_base::puppetagent::version: 'latest'
nextcloud::install_enabled: false
nextcloud::update_enabled: false
nextcloud::installroot: '/var/www/html/'
```

However the puppetrun still complains about an error in part of puppet code that should be ignored.
Log from puppet run:
```
# puppet agent -t
Info: Using environment 'sandbox'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Failed to apply catalog: Could not find dependency File[/var/www/html//nextcloud-26.0.2] for Archive[Extract archive: update to 26.0.2] (file: /etc/puppetlabs/code/environments/sandbox/modules/upstream/nextcloud/manifests/install/distribution.pp, line: 64)
```

**Comment by fraenki** [comment]
Thanks for reporting this issue! This should be fixed in https://github.com/markt-de/puppet-nextcloud/commit/adaae52f38f07fc2c7fd322c738f21607dacba37. I've added unit tests to ensure this functionality.
