### ISSUE TITLE
Support app configs

### ISSUE THREAD

**Issue by nmaludy** [markt-de/puppet-nextcloud#2]
Currently `nextcloud::config` only supports system configs. Would be great if you could also add config settings into apps using `php occ config:app:set`.

**Comment by fraenki** [comment]
Could you provide an example app config? Or multiple examples if possible, which would be useful to add this feature.Thanks.

**Comment by nmaludy** [comment]
@fraenki I actually have a PR sitting on my laptop, I'll see if I can submit it tonight or tomorrow!
