### ISSUE TITLE
Passwords aren't escaped properly

### ISSUE THREAD

**Issue by nmaludy** [markt-de/puppet-nextcloud#4]
The passwords here https://github.com/markt-de/puppet-nextcloud/blob/main/manifests/install.pp#L46-L48 aren't escaped properly , so if your password has special shell characters it will try to expand them and the password you _think_ you set probably won't work.

**Comment by fraenki** [comment]
@nmaludy Do you think https://github.com/markt-de/puppet-nextcloud/commit/222323bd9236b6f7c0258287abc1d306d22883cd is sufficient?

**Comment by nmaludy** [comment]
@fraenki yeah, that should work!

**Comment by fraenki** [comment]
released in 1.4.0
