### ISSUE TITLE
Add support for notify_push rust backend

### ISSUE THREAD

**Issue by oxc** [markt-de/puppet-nextcloud#5]
Nextcloud 21 comes with a new "Files High Performance Back-end", packaged in the form of a new [notify_push](https://github.com/nextcloud/notify_push) app.

Roughly, the setup works as follows:
1. Install app in nextcloud. This ships backend binaries for 3 platforms (aarch64, armv7 and x86_64).
2. Setup a daemon service that starts the backend service
3. Configure apache/nginx/whatever to proxy requests to `/push/` to the new service (the /push/ prefix must be stripped), including `/push/ws/` for websockets
4. Run `occ notify_push:setup` to verify the connection and enable usage of the new backend

At least the first two steps could be done by this module, behind a new `$manage_notify_push` flag.

The app comes with a setup-wizard that supports setting this up for systemd+apache/nginx based setups, but I don't think this is a feasible approach for integration into the module. Here is the code that generates the [systemd service file](https://github.com/nextcloud/notify_push/blob/main/lib/SetupWizard.php#L254). This should probably be done with camptocamp/systemd?

Attached is the [rc.d/nextcloud_notify_push](https://github.com/markt-de/puppet-nextcloud/files/6057383/nextcloud_notify_push.txt) I've whipped up for FreeBSD (at least the run user would have to be set by the template)

**Comment by oxc** [comment]
In case this might be interesting for you -- for haproxy, the following worked for me:

```haproxy
frontend www
    acl nextcloud-acl hdr(host) -i my.nextcloud.host
    use_backend nextcloud-push-backend if nextcloud-acl { path_beg /push/ }
    use_backend nextcloud-backend if nextcloud-acl

backend nextcloud-push-backend
    server nextcloud-push nextcloud.local:7867

    http-request replace-path /push/(.*) /\1

    mode http
```

**Comment by fraenki** [comment]
@oxc Could you give https://github.com/markt-de/puppet-nextcloud/pull/6 a try? I don't have Nextcloud v21 around, so I wasn't able to test it.

**Comment by oxc** [comment]
I get a permission denied on the pidfile, because now the daemon runs as www-data, not as root. `${name}_user` is automatically used by rc when running the `command`.

That's why I had the name hardcoded :D Perhaps we can just rename the variable to something like _service_user?

**Comment by oxc** [comment]
That's also the reason for the "my_flags" hack, which probably also doesn't make sense. I suggest we use $nextcloud_notify_push_service_flags and $nextcloud_notify_push_service_user

**Comment by fraenki** [comment]
> I get a permission denied on the pidfile, because now the daemon runs as www-data, not as root. ${name}_user is automatically used by rc when running the command.

That's odd. I was under the assumption that `daemon` creates the PID file as root, at least this is how I understand the man page:

>             The supervisor_pidfile owner is the user who runs
>             the daemon regardless of whether the -u option is used or not.

**Comment by oxc** [comment]
Yes, this is correct, but the user who runs daemon is www-data, because we re-use the automagic rc variable ${name}_user, which is what daemon is run as.

If you rename it to ${name}_serivce_user, everything should work as expected.

**Comment by oxc** [comment]
https://www.freebsd.org/cgi/man.cgi?query=rc.subr&sektion=8&n=1

```
		 ${name}_user
			   User	to run command as, using chroot(8) if
			   ${name}_chroot is set, otherwise uses su(1).	 Only
			   supported after /usr	is mounted.
```

**Comment by fraenki** [comment]
Got it, thanks.

**Comment by fraenki** [comment]
Does https://github.com/markt-de/puppet-nextcloud/pull/6/commits/9b13855d74772dec46f379a52ef555c7cc0dcbd2 sufficiently address all issues?

**Comment by oxc** [comment]
LGTM, I will test right away.

**Comment by oxc** [comment]
> Notice: /Stage[main]/Nextcloud::Hpb/Service[notify_push]/ensure: ensure changed 'stopped' to 'running'

Works just fine!

One last thing: should the service file/service be called nextcloud_notify_push, or did you deliberately choose notify_push even though the rc name is nextcloud_notify_push?

**Comment by fraenki** [comment]
> One last thing: should the service file/service be called nextcloud_notify_push, or did you deliberately choose notify_push even though the rc name is nextcloud_notify_push?

Good catch, it should be "nextcloud_notify_push", I'll push a fix.

**Comment by fraenki** [comment]
Fixed in https://github.com/markt-de/puppet-nextcloud/pull/6/commits/bae23338bc031b6912c5287915d55d9ae0a096e2.
I'll merge it now, but will probably let it sink for a few days before releasing v1.6.0.

**Comment by fraenki** [comment]
@oxc btw. thanks for the proposal and testing!

**Comment by oxc** [comment]
Thanks for the quick implementation!
